#!/bin/bash

EXECUTABLE=./virtualmachine

cp -r /autograder/submission/* /autograder/source/

pushd /autograder/source/ >/dev/null

# remove any tst, vm, or cmp files in submission
rm -f *.vm *.tst *.cmp

# run student-submitted setup script (untrusted)
chmod +x ./setup.sh
runuser -u student -- ./setup.sh

# in case setup.sh created hack files
rm -f *.asm *.cmp

chmod ugo+x "${EXECUTABLE}"

popd >/dev/null

# diff outputs with expected
cd /autograder/grader
uv run src/run_tests.py
