#!/bin/bash

EXECUTABLE=./VMTranslator

SUBMISSION_DIR=$(realpath $(dirname $(find /autograder/submission -name 'setup.sh' -type f)))
echo "Identified ${SUBMISSION_DIR} as root of project."
cp -r ${SUBMISSION_DIR}/* /autograder/source/

pushd /autograder/source/ >/dev/null

# remove any tst, vm, or cmp files in submission
rm -f *.vm *.tst *.cmp

# run student-submitted setup script (untrusted)
chmod +x ./setup.sh
runuser -u student -- ./setup.sh

# in case setup.sh created hack files
rm -f *.asm *.cmp

chmod ugo+x "${EXECUTABLE}"

popd >/dev/null

# diff outputs with expected
cd /autograder/grader
uv run src/run_tests.py
